import Head from "next/head";
import Link from "next/link";
import { SignUp, useUser, SignOutButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

const CreatePostWizzard = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return (
    <div className="flex w-full gap-2">
      <img
        src={user.profileImageUrl}
        className="h-16 w-16 rounded-full"
        alt="Profile Photo"
      />
      <input
        placeholder="Type something"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};
export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading</div>;

  return (
    <>
      <Head>
        <title>pecetApp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <div className="h-full w-full border-x border-slate-400 bg-slate-600 md:max-w-2xl">
          <div className="border-b border-slate-400 p-2">
            {!user.isSignedIn && (
              <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
            )}
            {!!user.isSignedIn && (
              <>
                <SignOutButton />
                <CreatePostWizzard />
              </>
            )}
          </div>
          <div className="flex flex-col gap-2">
            {data?.map(({ post, author }) => {
              return (
                <div key={post.id} className="flex gap-2 border-b p-2">
                  <p>{post.content}</p>
                  <p>{author!.username}</p>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
