import Head from "next/head";
import Link from "next/link";
import { SignUp, useUser, SignOutButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!user.isSignedIn && (
          <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
        )}
        {!!user.isSignedIn && <SignOutButton />}
      </main>
    </>
  );
}
